---
Name: shortcodable
After:
  - framework/*
  # - cms/*
---

SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'sheadawson/silverstripe-shortcodable:javascript/editor_plugin.js'
    - 'sheadawson/silverstripe-shortcodable:javascript/shortcodable.js'
  extra_requirements_css:
    - 'sheadawson/silverstripe-shortcodable:css/shortcodable.css'

SilverStripe\Control\Director:
  rules:
    'admin/shortcodable': Silverstripe\Shortcodable\Controller\ShortcodableController

Shortcodable:
  htmleditor_names:
    - cms

HtmlEditorField:
  extensions:
    - ShortcodableHtmlEditorField

ShortcodeParser:
  extensions:
    - ShortcodableShortcodeParserExtension
